version: '3'
services:
  server:
    depends_on:
      - www
    restart: always
    build: ./packages/server
    image: ly-editor
    environment:
      GCLOUD_JSON:
      PORT: 8080
    ports:
      - 8080:8080
  www:
    build: ./packages/www
    image: ly-www
